# Version format
version: 1.0.{build}

# Build worker image
image: Visual Studio 2019

# Build platform
platform: Any CPU

# Build Configuration
configuration: Debug

# MSBuild settings
build:
  project: TurtleTest.sln
  verbosity: quiet

# Execute script before build
before_build:
 - nuget restore TurtleTest.sln